### PR TITLE
DEV: Linting fixes

### PR DESCRIPTION
**Pull request by CvX**
Empty block statement, Don't use observers, Do not use volatile computed properties.

Not tested in any way yet. 😐 What's the recommended flow for trying out changes to docker_manager?

### CODE REVIEW

**Comment by eviltrout** [comment]
You should be able to run it locally - the README explains how to do it:

https://github.com/discourse/docker_manager#the-client-app

**Comment by eviltrout** [comment]
@CvX can you update this PR once you've confirmed it works locally?

**Comment by CvX** [comment]
omg, there's no facepalm emoji big enough for me 🤦 I must have mixed up plugins directories when looking this up, because there readme was empty and there were no frontend tests 😆

**Comment by SamSaffron** [comment]
@CvX closing this for now, mainly to keep our PR queue clearer, feel free to do a new PR here.

**Pull request closed without merging**
