### PR TITLE
Fix message bus when using a longPollingBaseUrl

### PR DESCRIPTION
**Pull request by chrispanag**
The trailing slash was missing from the longPollingBaseUrl causing the messageBus to fail.
So I just added the trailing slash :)

### CODE REVIEW

**Comment by jomaxro** [comment]
Thanks @chrispanag, I'm a bit confused why this is needed. The default `long_polling_base_url` is a `/`, so this change would result in double slashes for most sites. See [Discourse Site Settings](https://github.com/discourse/discourse/blob/master/config/site_settings.yml#L1486).

**Comment by chrispanag** [comment]
@jomaxro you are right on that, I'm completely new to contributing on Discourse, so thanks for the tip. 

The reason I contributed this is because on my Discourse forum (rembetiko.gr) where I use a longPollingUrl, the Docker-Manager, fails to do the `/poll` request to the backend. I traced the issue and I observed that the url of the ajax call was missing the trailing `/`. So that's why I contributed that.

After doing a bit of a research, I found this on the [message-bus initializer in the main Discourse app](https://github.com/discourse/discourse/blob/master/app/assets/javascripts/discourse/initializers/message-bus.js.es6) (Lines 52-53). 

```javascript
 messageBus.baseUrl =
      siteSettings.long_polling_base_url.replace(/\/$/, "") + "/";
```

This is inconsistent to this line from the message-bus initializer in Docker Manager: 

```javascript
MessageBus.baseUrl = Discourse.longPollingBaseUrl;
```
The `.replace(/\/$/, "")` will alleviate the issue you observed. So I'm modifying my commit to also include that :)

**Comment by chrispanag** [comment]
@jomaxro @SamSaffron I'm bumping this, as today is the planned release day of Discourse 2.3, so it could be a nice opportunity to merge this :)

**Comment by SamSaffron** [comment]
Yeah confirmed, this is exactly the same code we use in core. Merging this in. 

https://github.com/discourse/discourse/blob/03ba1d49fbdceaeec76301b0811daba5dca6cb94/app/assets/javascripts/discourse/initializers/message-bus.js.es6#L52-L53

**Pull request merged**
