### PR TITLE
FIX: Support git URLs without a .git extension

### PR DESCRIPTION
**Pull request by cpradio**

### CODE REVIEW

**Comment by SamSaffron** [comment]
I think this is ok but don't we need to rebuild the bundle @eviltrout  ?

**Comment by cpradio** [comment]
I had to in a prior PR...
https://github.com/discourse/docker_manager/pull/28

I couldn't see a spot where this was being done automatically. And when I altered my app.yml to point to my branch, it wouldn't take the change until I rebuilt the bundle.

**Comment by eviltrout** [comment]
Yes you need to run the `./compile_client.sh` or the changes won't take effect in production mode.

I've wanted to make this automatic for a while but alas :P

**Comment by eviltrout** [comment]
This still hasn't had the assets compiled right?

**Comment by cpradio** [comment]
No they are. See assets/docker-manager-app.js which is part of the PR

**Comment by eviltrout** [comment]
Great thanks!

**Pull request merged**
